language: c
sudo: false

env:
  - OCAML_VERSION=4.09

before_install:
  - sh <(curl -sL https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh)

install:
  - opam switch create dev --empty
  - eval $(opam env)
  - opam pin add -y ocaml-variants https://github.com/gretay-js/ocaml.git\#fdo409
  - opam pin add -y ocamlcfg https://github.com/gretay-js/ocamlcfg.git\#master

  - ocamlc -v

  - opam install -y ppx_jane core async

script:
  - dune build bin/main.exe
  - dune runtest
